apiVersion: apps/v1
kind: Deployment
metadata:
  name: genegraph
  labels:
    app: genegraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genegraph
  template:
    metadata:
      labels:
        app: genegraph
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - genegraph
            topologyKey: "kubernetes.io/hostname"
      containers:
        - image: gcr.io/clingen-dev/genegraph:v2
          name: genegraph
          livenessProbe:
            httpGet:
              path: /live
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: CG_SEARCH_DATA_VOL
              value: "/data/"
            - name: KAFKA_HOST
              value: "pkc-4yyd6.us-east1.gcp.confluent.cloud:9092"
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: user
            - name: KAFKA_PASS
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: password
            - name: CG_SEARCH_TOPICS
              value: gene_dosage_sepio_in
          ports:
            - containerPort: 8888
              name: genegraph
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/

              
  
