apiVersion: v1
kind: Service
metadata:
  labels:
    app: genegraph
  name: genegraph
spec:
  type: LoadBalancer
  loadBalancerIP: 35.243.230.124
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    app: genegraph
  
