- name: Install packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - openjdk-8-jdk
      - rsync
- name: Set java8 to default
  command: /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
- name: Setup group
  group:
    name: app
    system: yes
- name: Setup user
  user:
    name: app
    system: yes
    group: app
- name: Setup directory structure
  file:
    state: directory
    path: "{{ item }}"
    owner: app
    group: app
    mode: 0755
  loop:
    - "/app"
    - "/app/lib"
    - "/app/db"
    - "/app/keys"
    - "/app/state"
- name: Copy systemd unit
  template:
    src: search.service.j2
    dest: /etc/systemd/system/search.service



